#!/usr/bin/env python
# -*- coding: utf-8 -*-

from rdflib import Namespace, URIRef, Literal, Graph, XSD
from rdflib.namespace import RDF, FOAF
from ontologias import GR, VCARD, UMBEL
from lugares import g, rutaMaiz

facebook = Namespace('https://www.facebook.com/')
twitter = Namespace('https://www.twitter.com/')
maps = Namespace('https://goo.gl/maps/')
alcaldiaTulua = Namespace('http://www.tulua.gov.co/sitio.shtml?apc=m1r1--&x=')

def restaurantes(uri, nombre, menu, telefono, direccion, webpage, imagen, mapa, uriatencion, abre, cierra):
    if webpage != "No disponible":
        g.add( (URIRef(uri), FOAF.homepage, URIRef(webpage)) )
            
    g.add( (URIRef(uri), RDF.type, GR.Location) )
    g.add( (URIRef(uri), GR.name, Literal(nombre, lang='es')) )
    g.add( (URIRef(uri), GR.description, Literal(menu, lang='es')))
